# Generated by Django 4.2.13 on 2024-06-02 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_course_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='total_lechture',
            new_name='total_lecture',
        ),
    ]
