# Generated by Django 4.2.13 on 2024-06-04 08:05

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
