# Generated by Django 4.2.13 on 2024-06-04 10:04

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_testmonial_remove_teacher_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='slug',
            field=autoslug.fields.AutoSlugField(blank=True, editable=False, null=True, populate_from='name'),
        ),
    ]
